name: "random_forest"
estimator: "sklearn.ensemble.RandomForestClassifier"
params: {}   # (laisser vide si tu utilises param_grid)
param_grid:
  - { n_estimators: 50,  max_depth: null, random_state: 42 }
  - { n_estimators: 100, max_depth: 10,   random_state: 42 }
  - { n_estimators: 200, max_depth: 20,   random_state: 42 }
